import time
from appium import webdriver
from appium.options.common.base import AppiumOptions
from appium.webdriver.common.appiumby import AppiumBy

options = AppiumOptions()
options.load_capabilities({
	"platformName": "Android",
	"appium:deviceName": "emulator-5554",
	"appium:automationName": "UiAutomator2",
	"appium:appPackage": "com.saucelabs.mydemoapp.android"
})

driver = webdriver.Remote("http://127.0.0.1:4723", options=options)
time.sleep(4)

el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().resourceId(\"com.saucelabs.mydemoapp.android:id/productIV\").instance(0)")
el1.click()
time.sleep(1)
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Green color")
el2.click()
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Increase item quantity")
el3.click()
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Tap to add product to cart")
el4.click()
time.sleep(2)
el5 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/cartIV")
el5.click()
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Decrease item quantity")
el6.click()
el7 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Confirms products for checkout")
el7.click()
time.sleep(1)
el8 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/nameET")
el8.send_keys("UserTest")
el9 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/passwordET")
el9.send_keys("PasswordTest")
time.sleep(1)
el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Tap to login with given credentials")
el10.click()
time.sleep(1)
el11 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/fullNameET")
el11.send_keys("Name")
el12 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/address1ET")
el12.send_keys("Address")
el13 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/cityET")
el13.send_keys("City")
el14 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/zipET")
el14.send_keys("1234123")
el15 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/countryET")
el15.send_keys("Country")
time.sleep(1)
el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Saves user info for checkout")
el16.click()
time.sleep(1)
el17 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/nameET")
el17.send_keys("Full Name")
el18 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/cardNumberET")
el18.send_keys("123123123123")
el19 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/expirationDateET")
el19.send_keys("12/26")
el20 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/securityCodeET")
el20.send_keys("123")
time.sleep(1)
el21 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Saves payment info and launches screen to review checkout data")
el21.click()
time.sleep(1)
el22 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Completes the process of checkout")
el22.click()
time.sleep(1)
el23 = driver.find_element(by=AppiumBy.ID, value="com.saucelabs.mydemoapp.android:id/completeTV")
print(el23.text)
print(el23.is_displayed())
time.sleep(5)
driver.quit()